version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
        - "6379:6379"
    expose:
        - "6379"
  web:
      build: .
      command: python sneaky/manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      links:
        - redis